baseURL = "/"
languageCode = "en-uk"
title = "Research Software Alliance"
theme = "syna"

# Google Analytics tracking
googleAnalytics = "G-P9VQSP6L49"

[params]
  twitter = "https://twitter.com/researchsoft"
  github = "https://github.com/researchsoft"
  site_logo = "img/resa-logo-software-green.png"
  name = "The Research Software Alliance"

  [params.colors]
    primary = "darkgreen"
    secondary = "darkorange"

[[menu.main]]
  url = "/about-resa"
  name = "About"
  weight = 10

[[menu.main]]
  url = "/people"
  name = "People"
  weight = 20

[[menu.main]]
  url = "/taskforces"
  name = "Task forces"
  weight = 30

[[menu.main]]
  url = "/resa-resources"
  name = "Resources"
  weight = 40

[[menu.main]]
  url = "/news"
  name = "News"
  weight = 50

[[menu.main]]
  url = "/contact"
  name = "Contact"
  weight = 60

[[menu.footer]]
  url = "/code-of-conduct"
  name = "Code of Conduct"
  weight = 60
  color = "primary"
  
[[menu.footer]]
  url = "/license"
  name = "License"
  weight = 70
  color = "primary"
  
[[menu.footer_social]]
  weight = 20
  name = "twitter"
  url = "https://twitter.com/researchsoft"
  pre = "fab fa-twitter"

[[menu.footer_social]]
  weight = 30
  name = "github"
  url = "https://github.com/researchsoft/website"
  pre = "fab fa-github fa-stack-2x"
