baseURL = "https://researchsoft.org"
# Google Analytics tracking
googleAnalytics = "UA-181241343-1"

languageCode = "en-uk"
LanguageCode = "en-uk"
title = "Research Software Alliance"
theme = "syna"
enableGitInfo = true
version = "0.17.3"
rssLimit = 100

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputs]
  home = ["ATOM", "HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName  = "feed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  github = "https://github.com/researchsoft"
  site_logo = "img/resa-logo-software-green.png"
  name = "The Research Software Alliance"

  date_format = "January 2, 2006"
  dateFormatAtomFeed = "2006-01-02T15:04:05-07:00"
  dateFormatTag = "2006"
  feedUUID = "283aaa54-faf6-4bcd-9cb8-74a13b96063c"
  # icon = ""
  # icon96 = ""
  # logo = "img/resa-logo-software-green.png"
  mainSections = ["blog"]
  buildFuture = true


  [params.colors]
    primary = "darkgreen"
    secondary = "darkorange"

[[menu.main]]
  identifier = "/about-resa"
  name = "About"
  weight = 10

[[menu.main]]
  parent = "/about-resa"
  url = "/about-resa"
  name = "About"
  weight = 11

[[menu.main]]
    parent = "/about-resa"
    url = "/governance"
    name = "Governance"
    weight = 12

[[menu.main]]
  parent = "/about-resa"
  url = "/our-team"
  name = "Our Team"
  weight = 13

[[menu.main]]
  parent = "/about-resa"
  url = "/membership"
  name = "Organisational Membership"
  weight = 14

[[menu.main]]
  parent = "/about-resa"
  url = "/stakeholders"
  name = "Stakeholders"
  weight = 15  

[[menu.main]]
  parent = "/about-resa"
  url = "/donate"
  name = "Donate"
  weight = 16

[[menu.main]]
  identifier = "/taskforces"
  name = "Task Forces"
  weight = 20

[[menu.main]]
  parent = "/taskforces"
  url = "/taskforces"
  name = "About Task Forces"
  weight = 21

 [[menu.main]]
  parent = "/taskforces"
  url = "/tf-support"
  name = "Task Force Support"
  weight = 22

[[menu.main]]
  identifier = "/forums"
  name = "Forums"
  weight = 30

[[menu.main]]
  parent = "/forums"
  url = "/funders-forum"
  name = "Research Software Funders Forum"
  weight = 31

[[menu.main]]
  parent = "/forums"
  url = "/RSI-forum"
  name = "Research Software Infrastructure Forum"
  weight = 32

  [[menu.main]]
  parent = "/forums"
  url = "/rsp-forum"
  name = "Research Software Policy Forum"
  weight = 33 

  [[menu.main]]
  parent = "/forums"
  url = "/mars-forum"
  name = "Metascience and Research Software Forum"
  weight = 34  

  [[menu.main]]
  parent = "/forums"
  url = "/pubsoft-forum"
  name = "Publishing Research Software Forum"
  weight = 35 

[[menu.main]]
  parent = "/forums"
  url = "/stars-forum"
  name = "Skills and Training for Research Software Forum"
  weight = 36
  
[[menu.main]]
  parent = "/forums"
  url = "https://adore.software/"
  name = "ADORE.software Secretariat"
  weight = 37

[[menu.main]]
  parent = "/forums"
  url = "https://researchsoftware.org/council.html"
  name = "International Council of RSE Associations"
  weight = 38
  
[[menu.main]]
  parent = "/forums"
  url = "/community-forum"
  name = "Community Leaders Forum"
  weight = 39

[[menu.main]]
  identifier = "/resa-resources"
  url = "/resa-resources"
  name = "Resources"
  weight = 40

[[menu.main]]
  parent = "/resa-resources"
  name = "Resources"
  url = "/resa-resources"
  weight = 41

[[menu.main]]
  parent = "/resa-resources"
  name = "Guidelines"
  url = "/guidelines"
  weight = 42

[[menu.main]]
  parent = "/resa-resources"
  name = "Funding Opportunities"
  url = "/funding-opportunities"
  weight = 43
  
[[menu.main]]
  parent = "/resa-resources"
  name = "Software Policies"
  url = "/software-policies"
  weight = 44

[[menu.main]]
  parent = "/resa-resources"
  name = "ADORE.software Declaration"
  url = "https://adore.software/"
  weight = 45

[[menu.main]]
  parent = "/resa-resources"
  name = "Research Software Engineers (RSEs)"
  url = "/research-software-engineers"
  weight = 46  
  
[[menu.main]]
  url = "/news"
  name = "News"
  weight = 50

[[menu.main]]
  url = "/events"
  name = "Events"
  weight = 60

[[menu.main]]
    url = "/blog"
    name = "Blog"
    weight = 70

[[menu.footer_social]]
  weight = 30
  name = "github"
  url = "https://github.com/researchsoft/website"
  pre = "fab fa-github fa-stack-2x"

[[menu.footer_social]]
  weight = 40
  name = "email"
  url = "/contact/"
  pre = "fa fa-envelope"

[[menu.footer_social]]
  weight = 50
  name = "slack"
  url = "https://join.slack.com/t/researchsoft/shared_invite/zt-1flmrglww-SoWjAK_5TJyqLU_~Jx697w"
  pre = "fab fa-slack"

[[menu.footer_social]]
  weight = 60
  name = "Mastodon"
  url = "https://fosstodon.org/@researchsoft"
  pre = "fab fa-mastodon"

[[menu.footer_social]]
  weight = 60
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/research-software-alliance"
  pre = "fab fa-linkedin"  

[[menu.footer_social]]
  weight = 70
  name = "Atom Feed"
  url = "/feed.xml"
  pre = "fa fa-rss"

[[menu.copyright_footer]]
  url = "/license"
  name = "License"
  weight = 60
  color = "primary"

[[menu.copyright_footer]]
  url = "/code-of-conduct"
  name = "Code of Conduct"
  weight = 70
  color = "primary"

[author]
  name = "Research Software Alliance"
